import { RevenueRiskEvent, AIDecision, Transaction, RecoveryOpportunity } from '../types';

export const MOCK_SUMMARY = {
  totalRiskAmount: 148500,
  totalRecoveredAmount: 104250,
  activeRiskCount: 38,
  aiDecisionsExecuted: 184,
  recoveryRate: 70.2,
  currency: 'USD',
};

export const MOCK_RISK_EVENTS: RevenueRiskEvent[] = [
  {
    id: 'risk_01H9A123',
    merchant_id: 'merchant_acme_01',
    event_type: 'failed_payment',
    severity: 'high',
    status: 'in_recovery',
    amount: 2450.00,
    currency: 'USD',
    customer_id: 'cust_9921',
    customer_email: 'sarah.j@enterprise.com',
    transaction_id: 'txn_881239',
    risk_score: 0.89,
    detected_at: '2026-08-21T14:32:00Z',
    updated_at: '2026-08-21T15:10:00Z',
    metadata: {
      decline_code: 'insufficient_funds',
      gateway: 'Razorpay',
      attempts_count: 2,
    },
  },
  {
    id: 'risk_01H9A124',
    merchant_id: 'merchant_acme_01',
    event_type: 'abandoned_cart',
    severity: 'medium',
    status: 'open',
    amount: 890.00,
    currency: 'USD',
    customer_id: 'cust_4410',
    customer_email: 'alex.m@techcorp.io',
    risk_score: 0.65,
    detected_at: '2026-08-21T16:05:00Z',
    updated_at: '2026-08-21T16:05:00Z',
    metadata: {
      items_count: 3,
      cart_value: 890.00,
      checkout_stage: 'payment_step',
    },
  },
  {
    id: 'risk_01H9A125',
    merchant_id: 'merchant_acme_01',
    event_type: 'subscription_leak',
    severity: 'high',
    status: 'open',
    amount: 5000.00,
    currency: 'USD',
    customer_id: 'cust_1002',
    customer_email: 'finance@globalcorp.org',
    risk_score: 0.94,
    detected_at: '2026-08-21T11:20:00Z',
    updated_at: '2026-08-21T11:20:00Z',
    metadata: {
      plan_name: 'Enterprise Tier',
      churn_signal: 'payment_method_expired',
    },
  },
  {
    id: 'risk_01H9A126',
    merchant_id: 'merchant_acme_01',
    event_type: 'chargeback_risk',
    severity: 'critical',
    status: 'in_recovery',
    amount: 3200.00,
    currency: 'USD',
    customer_id: 'cust_8831',
    customer_email: 'david.k@luxuryshop.com',
    transaction_id: 'txn_994112',
    risk_score: 0.96,
    detected_at: '2026-08-20T18:45:00Z',
    updated_at: '2026-08-21T09:00:00Z',
    metadata: {
      dispute_reason: 'unrecognized_charge',
      gateway: 'Stripe',
    },
  },
  {
    id: 'risk_01H9A127',
    merchant_id: 'merchant_acme_01',
    event_type: 'failed_payment',
    severity: 'medium',
    status: 'resolved',
    amount: 1200.00,
    currency: 'USD',
    customer_id: 'cust_3301',
    customer_email: 'billing@saassolutions.co',
    transaction_id: 'txn_771004',
    risk_score: 0.72,
    detected_at: '2026-08-19T09:15:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    metadata: {
      recovered_via: 'smart_retry_schedule',
    },
  },
];

export const MOCK_AI_DECISIONS: AIDecision[] = [
  {
    id: 'dec_9901',
    merchant_id: 'merchant_acme_01',
    risk_event_id: 'risk_01H9A123',
    action_type: 'smart_retry_schedule',
    confidence_score: 0.94,
    reasoning: 'Customer account shows active usage pattern. Card retry recommended at 18:00 UTC based on historical bank approval rates.',
    payload: {
      retry_delay_hours: 4,
      target_gateway: 'Razorpay',
      fallback_action: 'send_dunning_email',
    },
    status: 'executed',
    executed_at: '2026-08-21T15:10:00Z',
    created_at: '2026-08-21T14:35:00Z',
  },
  {
    id: 'dec_9902',
    merchant_id: 'merchant_acme_01',
    risk_event_id: 'risk_01H9A125',
    action_type: 'personalized_dunning',
    confidence_score: 0.88,
    reasoning: 'High-value enterprise customer with expired card. Recommend sending priority updating link with account manager copied.',
    payload: {
      email_template: 'enterprise_card_update',
      discount_offered_percent: 0,
      urgent: true,
    },
    status: 'pending_approval',
    created_at: '2026-08-21T11:22:00Z',
  },
  {
    id: 'dec_9903',
    merchant_id: 'merchant_acme_01',
    risk_event_id: 'risk_01H9A126',
    action_type: 'chargeback_prevention_offer',
    confidence_score: 0.92,
    reasoning: 'Immediate customer reach-out with transaction evidence to resolve inquiry before formal chargeback filing.',
    payload: {
      offer_full_refund: false,
      offer_credit_amount: 100,
    },
    status: 'executed',
    executed_at: '2026-08-21T09:00:00Z',
    created_at: '2026-08-20T18:50:00Z',
  },
];

export const MOCK_RECOVERY_OPPORTUNITIES: RecoveryOpportunity[] = [
  {
    id: 'opp_01',
    title: 'Smart Card Retry Engine',
    description: 'Autonomous retry algorithm for failed recurring subscription charges tuned to bank response signals.',
    potential_revenue: 42500,
    success_rate: 68.5,
    risk_type: 'failed_payment',
    recommended_action: 'Execute Autonomous Retry Schedule',
    status: 'active',
  },
  {
    id: 'opp_02',
    title: 'Dynamic Cart Abandonment Re-engagement',
    description: 'AI-driven personalized incentive email sequences targeting high-value checkout drop-offs.',
    potential_revenue: 28900,
    success_rate: 44.2,
    risk_type: 'abandoned_cart',
    recommended_action: 'Trigger Smart Email Sequence',
    status: 'active',
  },
  {
    id: 'opp_03',
    title: 'Enterprise Dunning & Billing Update',
    description: 'High-touch automated dunning flow for B2B accounts with expired credit cards.',
    potential_revenue: 35000,
    success_rate: 81.0,
    risk_type: 'subscription_leak',
    recommended_action: 'Deploy Account Manager Dunning',
    status: 'active',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_881239',
    merchant_id: 'merchant_acme_01',
    customer_id: 'cust_9921',
    amount: 2450.00,
    currency: 'USD',
    status: 'failed',
    gateway: 'Razorpay',
    gateway_transaction_id: 'pay_N9281A',
    error_code: 'insufficient_funds',
    risk_flag: true,
    created_at: '2026-08-21T14:32:00Z',
  },
  {
    id: 'txn_994112',
    merchant_id: 'merchant_acme_01',
    customer_id: 'cust_8831',
    amount: 3200.00,
    currency: 'USD',
    status: 'disputed',
    gateway: 'Stripe',
    gateway_transaction_id: 'ch_3M9201',
    risk_flag: true,
    created_at: '2026-08-20T18:45:00Z',
  },
  {
    id: 'txn_771004',
    merchant_id: 'merchant_acme_01',
    customer_id: 'cust_3301',
    amount: 1200.00,
    currency: 'USD',
    status: 'succeeded',
    gateway: 'Razorpay',
    gateway_transaction_id: 'pay_M11099',
    risk_flag: false,
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'txn_662190',
    merchant_id: 'merchant_acme_01',
    customer_id: 'cust_1105',
    amount: 450.00,
    currency: 'USD',
    status: 'succeeded',
    gateway: 'Stripe',
    gateway_transaction_id: 'ch_4L1992',
    risk_flag: false,
    created_at: '2026-08-21T16:40:00Z',
  },
];
